---
image: swedishembedded/build:v0.26.4-1

default:
  tags:
    - docker

stages:
 - build

# This job builds applications
build:
    stage: build
    before_script:
        - apt-get update
        - apt-get install -q -y coccinelle
    script:
        - make check
